business_tracker/apps/accounts/urls.py
from django.urls import path
from apps.accounts import views

app_name = "accounts"

urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("password/reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("password/reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(), name="password_reset"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:uid>/password/change/", views.PasswordChangeView.as_view(), name="password_change"),
    path("<int:uid>/", views.DetailView.as_view(), name="detail"),
    path("<int:uid>/edit/", views.EditView.as_view(), name="edit"),
    path("<int:uid>/delete/", views.DeleteView.as_view(), name="delete"),
    path("<int:uid>/type/", views.TypeView.as_view(), name="type"),
    path("<int:uid>/activate/", views.ActivateView.as_view(), name="activate"),
    path("shifts/create/", views.CreateShiftView.as_view(), name="shifts_create"),
    path("shifts/<int:uid>/edit/", views.EditShiftView.as_view(), name="shifts_edit"),
    path("shifts/<int:uid>/delete/", views.DeleteShiftView.as_view(), name="shifts_delete"),
]

business_tracker/apps/projects/urls.py
from django.urls import path
from apps.projects import views

app_name = "projects"

urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:uid>/", views.DetailView.as_view(), name="detail"),
    path("<int:uid>/edit/", views.EditView.as_view(), name="edit"),
    path("<int:uid>/delete/", views.DeleteView.as_view(), name="delete"),
    path("<int:uid>/generate/ros/", views.GenerateROSView.as_view(), name="generate_ros"),
]

business_tracker/common/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from common import views

urlpatterns = [
    path("accounts/", include("apps.accounts.urls")),
    path("invoices/", include("apps.invoices.urls")),
    path("partners/", include("apps.partners.urls")),
    path("projects/", include("apps.projects.urls")),
    path("servers/", include("apps.servers.urls")),
    path("settings/", views.SettingsView.as_view(), name="settings"),
    path("settings/dump/json/", views.DumpJsonView.as_view(), name="dump_json"),
    path("settings/dump/xml/", views.DumpXmlView.as_view(), name="dump_xml"),
    path("settings/reset/invoice/template/", views.ResetInvoiceTemplateView.as_view(), name="reset_invoice_template"),
    path("", login_required(TemplateView.as_view(template_name="dashboard.html")), name="dashboard"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

business_tracker/apps/projects/models.py
import datetime
from decimal import Decimal
from django.db import models
from django.utils.html import mark_safe
from apps.partners.models import Partner


class Project(models.Model):
    uid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=64)
    description = models.TextField(blank=True)
    due_date = models.DateField(blank=True, null=True, help_text="Can be left empty")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    @property
    def is_due(self):
        if self.due_date is not None and datetime.date.today() > self.due_date:
            return True
        return False

    def get_balance(self):
        total = Decimal("0.00")
        return total

    def get_tracked_time(self):
        time = 0
        for shift in self.shifts.all():
            time += shift.duration
        hours = time // 3600
        minutes = time % 3600 // 60
        return f"{hours:02d}:{minutes:02d}"

business_tracker/apps/projects/forms.py
import datetime
from django import forms
from apps.projects.models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = "__all__"
        labels = {"due_date": "Due Date"}


class GenerateROSForm(forms.Form):
    start_date = forms.DateField(label="Start Date")
    end_date = forms.DateField(label="End Date")

    def clean(self):
        if self.errors:
            return
        if self.cleaned_data["start_date"] > self.cleaned_data["end_date"]:
            raise forms.ValidationError("The start date cannot be greater than the end date.")
        return self.cleaned_data

business_tracker/apps/projects/views.py
import datetime
from django.views import View
from django.forms import ValidationError
from django.shortcuts import render, reverse
from django.contrib import messages
from django.http import HttpResponseRedirect
from common.mixins import AccessModelMixin, PermissionsRequiredMixin, NextPageMixin
from apps.projects.models import Project
from apps.projects.forms import ProjectForm, GenerateROSForm


class ListView(PermissionsRequiredMixin, View):
    def get(self, request):
        projects = Project.objects.all()
        return render(request=request, template_name="projects/list.html", context={"projects": projects})


class CreateView(PermissionsRequiredMixin, NextPageMixin, View):
    superuser = True

    def get(self, request):
        form = ProjectForm()
        return render(request=request, template_name="projects/create.html", context={"form": form})

    def post(self, request):
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "The project has been successfully created.")
            return HttpResponseRedirect(self.next)
        return render(request=request, template_name="projects/create.html", context={"form": form})


class DetailView(PermissionsRequiredMixin, AccessModelMixin, View):
    model = Project

    def get(self, request):
        dates = request.session.get("dates", None)
        services = None
        if dates:
            services = (
                self.project.shifts.filter(date__gte=datetime.date.fromisoformat(dates["start_date"]))
                .filter(date__lte=datetime.date.fromisoformat(dates["end_date"]))
                .order_by("-date")
            )
            request.session.pop("dates")
        return render(
            request=request,
            template_name="projects/detail.html",
            context={"project": self.project, "services": services},
        )


class EditView(PermissionsRequiredMixin, AccessModelMixin, NextPageMixin, View):
    superuser = True
    model = Project

    def get(self, request):
        form = ProjectForm(instance=self.project)
        return render(request=request, template_name="projects/edit.html", context={"form": form})

    def post(self, request):
        form = ProjectForm(request.POST, instance=self.project)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "The project has been successfully edited.")
            return HttpResponseRedirect(self.next)
        return render(request=request, template_name="projects/edit.html", context={"form": form})


class DeleteView(PermissionsRequiredMixin, AccessModelMixin, NextPageMixin, View):
    superuser = True
    model = Project

    def get(self, request):
        return render(request=request, template_name="projects/delete.html")

    def post(self, request):
        self.project.delete()
        messages.add_message(request, messages.SUCCESS, "The project has been deleted.")
        return HttpResponseRedirect(self.next)


class GenerateROSView(PermissionsRequiredMixin, AccessModelMixin, View):
    model = Project

    def get(self, request):
        form = GenerateROSForm()
        return render(request=request, template_name="projects/generate/ros.html", context={"form": form})

    def post(self, request):
        form = GenerateROSForm(request.POST)
        if form.is_valid():
            dates = (
                self.project.shifts.filter(date__gte=form.cleaned_data["start_date"])
                .filter(date__lte=form.cleaned_data["end_date"])
                .order_by("-date")
                .count()
            )
            if dates:
                request.session["dates"] = {
                    "start_date": form.cleaned_data["start_date"].isoformat(),
                    "end_date": form.cleaned_data["end_date"].isoformat(),
                }
                return HttpResponseRedirect(reverse("projects:detail", kwargs={"uid": self.project.uid}))
            form.add_error(field=None, error=ValidationError("There is not data available in this interval."))
        return render(request=request, template_name="projects/generate/ros.html", context={"form": form})

business_tracker/apps/projects/templates/projects/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block extra_head %}
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css">
{% endblock extra_head %}

{% block title %}Create Project{% endblock title %}
{% block subtitle %}Create a new project.{% endblock subtitle %}

{% block content %}
<form novalidate method="post">
    {% csrf_token %}
    {% if form.non_field_errors %}
    <div class="alert alert-block alert-danger">
        <ul class="m-0">
            {{ form.non_field_errors|unordered_list }}
        </ul>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-12 col-xl-6">
            {{ form.name|as_crispy_field }}
        </div>
        <div class="col-12 col-xl-6">
            {{ form.due_date|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            {{ form.description|as_crispy_field }}
        </div>
    </div>
    <hr>
    <div class="form-actions">
        <button type="submit" class="btn btn-success btn-detail">
            <i class="fas fa-check fa-fw mr-1"></i>
            Save
        </button>
        <a class="btn btn-secondary btn-detail" href="{{ request.GET.next }}">
            <i class="fas fa-times-circle fa-fw mr-1"></i>
            Cancel
        </a>
    </div>
</form>
<script>
    $('#id_due_date').datepicker({
        uiLibrary: 'bootstrap4',
        modal: true,
        format: 'yyyy-mm-dd',
        icons: { rightIcon: '<i class="fas fa-calendar-day"></i>' }
    });
</script>
{% endblock content %}

business_tracker/apps/projects/templates/projects/delete.html
{% extends "base.html" %}

{% block title %}Delete Project{% endblock title %}
{% block subtitle %}The project data will be deleted.{% endblock subtitle %}

{% block content %}
<form novalidate method="post">
    {% csrf_token %}
    <div class="form-group">
        <p>
            Are you sure you want to proceed?
            <br>
            This action is <span class="text-danger">irreversible</span>.
        </p>
    </div>
    <hr>
    <div class="form-actions">
        <button type="submit" class="btn btn-danger btn-detail">
            <i class="fas fa-trash fa-fw mr-1"></i>
            Delete
        </button>
        <a class="btn btn-secondary btn-detail" href="{% firstof request.GET.cancel request.GET.next %}">
            <i class="fas fa-times-circle fa-fw mr-1"></i>
            Cancel
        </a>
    </div>
</form>
{% endblock content %}

business_tracker/apps/projects/templates/projects/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ project.name }}{% endblock title %}
{% block subtitle %}View details about the project.{% endblock subtitle %}

{% block content %}
<div class="container-fluid no-gutters">
    <div class="row pt-3">
        <div class="col-xl-6 px-0 pr-xl-3">
            <h2>Project Information</h2>
            <table class="table">
                <tbody>
                    <tr>
                        <th scope="row">Name</th>
                        <td>{{ project.name }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Due Date</th>
                        <td>
                            {% if project.is_due %}
                            <span class="text-danger">{{ project.due_date }}</span>
                            {% else %}
                            {{ project.due_date|default_if_none:"N/A" }}
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Balance</th>
                        <td>${{ project.get_balance }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Tracked Time</th>
                        <td>{{ project.get_tracked_time }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-xl-6 px-0 pl-xl-3">
            <h2>Work Shifts</h2>
            <table id="jsDetailTable" class="table table-sm nowrap" style="width: 100%;">
                <thead>
                    <tr>
                        <th scope="col">Description</th>
                        <th scope="col">Duration</th>
                        <th scope="col">Date</th>
                        <th scope="col">Worker</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {% for shift in project.shifts.all %}
                    <tr>
                        <td data-toggle="tooltip" title="{{ shift.description }}">{{ shift.description|truncatechars:16 }}</td>
                        <td>{{ shift }}</td>
                        <td>{{ shift.date }}</td>
                        <td><a href="{% url 'accounts:detail' uid=shift.worker.uid %}">{{ shift.worker }}</a></td>
                        <td>
                            {% if request.user.uid == shift.worker.uid or request.user.is_superuser %}
                            <a class="btn btn-sm btn-warning"
                                href="{% url 'accounts:shifts_edit' uid=shift.uid %}?next={{ request.get_full_path }}" data-toggle="tooltip"
                                title="Edit Shift">
                                <i class="fas fa-pen fa-fw"></i>
                            </a>
                            <a class="btn btn-sm btn-danger"
                                href="{% url 'accounts:shifts_delete' uid=shift.uid %}?next={{ request.get_full_path }}"
                                data-toggle="tooltip" title="Delete Shift">
                                <i class="fas fa-trash fa-fw"></i>
                            </a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<hr>
<div class="container-fluid no-gutters">
    <div class="row">
        <a class="btn btn-dark btn-detail" href="{% url 'projects:list' %}">
            <i class="fas fa-arrow-left"></i>
        </a>
        <a class="btn btn-primary btn-detail mx-2"
            href="{% url 'projects:generate_ros' uid=project.uid %}?next={{ request.get_full_path }}">
            <i class="fas fa-list-alt fa-fw mr-1"></i>
            Generate Record of Services
        </a>
        {% if user.is_superuser %}
        <a class="btn btn-warning btn-detail mx-2" href="{% url 'projects:edit' uid=project.uid %}?next={{ request.get_full_path }}">
            <i class="fas fa-pen fa-fw mr-1"></i>
            Edit Project
        </a>
        <a class="btn btn-danger btn-detail mx-2"
            href="{% url 'projects:delete' uid=project.uid %}?next=/projects/&cancel={{ request.get_full_path }}">
            <i class="fas fa-trash fa-fw mr-1"></i>
            Delete Project
        </a>
        {% endif %}
    </div>
</div>
{% if services %}
<div class="modal fade" id="rosModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="record-of-services">Record of Services</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="pdf-area">
                <table id="rosTable" class="table table-sm table-bordered nowrap" style="width: 100%;">
                    <thead>
                        <tr>
                            <th>Account</th>
                            <th>Date</th>
                            <th>Service</th>
                            <th>Duration</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for service in services %}
                        <tr>
                            <td>{{ service.worker }}</td>
                            <td>{{ service.date|date:"Y-m-d" }}</td>
                            <td>{{ service.description }}</td>
                            <td>{{ service }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="copyToClipboard">Copy to clipboard</button>
                <button type="button" class="btn btn-secondary" id="exportToCSV">Export to CSV</button>
                <button type="button" class="btn btn-secondary" id="exportToPDF">Export to PDF</button>
            </div>
        </div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const table = document.getElementById('rosTable');
        const exportBtnCsv = document.getElementById('exportToCSV');
        const exportBtnPdf = document.getElementById('exportToPDF');
        const copyBtn = document.getElementById('copyToClipboard');

        function toClipboard() {
            var body = document.body, range, sel;
            if (document.createRange && window.getSelection) {
                range = document.createRange();
                sel = window.getSelection();
                sel.removeAllRanges();
                try {
                    range.selectNodeContents(table);
                    sel.addRange(range);
                } catch (e) {
                    range.selectNode(table);
                    sel.addRange(range);
                }
            } else if (body.createTextRange) {
                range = body.createTextRange();
                range.moveToElementText(table);
                range.select();
            }
            document.execCommand("copy");
            if (window.getSelection) { window.getSelection().removeAllRanges(); }
            else if (document.selection) { document.selection.empty(); }
        }

        function toCSV() {
            const rows = table.querySelectorAll('tr');
            const csv = [].slice.call(rows)
                .map(function (row) {
                    const cells = row.querySelectorAll('th,td');
                    return [].slice.call(cells)
                        .map(function (cell) {
                            return cell.textContent;
                        })
                        .join(',');
                })
                .join('\n');

            const link = document.createElement('a');
            link.setAttribute('href', `data:text/csv;charset=utf-8,${encodeURIComponent(csv)}`);
            link.setAttribute('download', 'Record of Services.csv');
            link.style.display = 'none';
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
        };

        function toPDF() {
            document.body.innerHTML = document.getElementById("pdf-area").innerHTML;
            document.title='Record of Services'; 
            window.print();
            location.reload()
        }

        exportBtnCsv.addEventListener('click', function () {
            toCSV();
        });

        copyBtn.addEventListener('click', function () {
            toClipboard();
        });
        
        exportBtnPdf.addEventListener('click', function () {
            toPDF();
        });
        
    });
</script>
{% endif %}
<script>
    table = $('#jsDetailTable').DataTable({
        responsive: true,
        dom: '<"row no-gutters flex-nowrap"<"flex-grow-1"f><"flex-shrink-0 ml-1"p>>t',
        pagingType: "numbers",
        pageLength: 10,
        ordering: false,
        language: {
            lengthMenu: "_MENU_",
            search: "_INPUT_",
            searchPlaceholder: "Search"
        },
        columnDefs: [
            {
                targets: [0, -1],
                responsivePriority: 1
            }]
    });
    $('#jsDetailTable_filter').removeClass('dataTables_filter');
    $('#jsDetailTable_filter > label').contents().unwrap();
</script>
{% endblock content %}

business_tracker/apps/projects/templates/projects/edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block extra_head %}
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css">
{% endblock extra_head %}

{% block title %}Edit Project{% endblock title %}
{% block subtitle %}Edit the project.{% endblock subtitle %}

{% block content %}
<form novalidate method="post">
    {% csrf_token %}
    {% if form.non_field_errors %}
    <div class="alert alert-block alert-danger">
        <ul class="m-0">
            {{ form.non_field_errors|unordered_list }}
        </ul>
    </div>
    {% endif %}
    <div class="row">
        <div class="col-12 col-xl-6">
            {{ form.name|as_crispy_field }}
        </div>
        <div class="col-12 col-xl-6">
            {{ form.due_date|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            {{ form.description|as_crispy_field }}
        </div>
    </div>
    <hr>
    <div class="form-actions">
        <button type="submit" class="btn btn-success btn-detail">
            <i class="fas fa-check fa-fw mr-1"></i>
            Save
        </button>
        <a class="btn btn-secondary btn-detail" href="{{ request.GET.next }}">
            <i class="fas fa-times-circle fa-fw mr-1"></i>
            Cancel
        </a>
    </div>
</form>
<script>
    $('#id_due_date').datepicker({
        uiLibrary: 'bootstrap4',
        modal: true,
        format: 'yyyy-mm-dd',
        icons: { rightIcon: '<i class="fas fa-calendar-day"></i>' }
    });
</script>
{% endblock content %}

business_tracker/apps/projects/templates/projects/list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Projects{% endblock title %}
{% block subtitle %}View the list of all projects.{% endblock subtitle %}

{% block content %}
<table id="jsTable" class="table list-view nowrap" style="width: 100%;">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Due Date</th>
            <th scope="col">Balance</th>
            <th scope="col">Tracked Time</th>
            <th scope="col">
                <a class="btn btn-sm btn-success" href="{% url 'projects:create' %}?next={{ request.get_full_path }}">
                    <i class="fas fa-plus fa-fw"></i>
                    Create Project
                </a>
            </th>
        </tr>
    </thead>
    <tbody>
        {% for project in projects %}
        <tr>
            <td>{{ project.name }}</td>
            <td>
                {% if project.is_due %}
                <span class="text-danger">{{ project.due_date }}</span>
                {% else %}
                {{ project.due_date|default_if_none:"N/A" }}
                {% endif %}
            </td>
            <td>${{ project.get_balance }}</td>
            <td>{{ project.get_tracked_time }}</td>
            <td>
                <a class="btn btn-sm btn-info" href="{% url 'projects:detail' uid=project.uid %}" data-toggle="tooltip"
                    title="View Project">
                    <i class="fas fa-eye fa-fw"></i>
                </a>
                <a class="btn btn-sm btn-warning" href="{% url 'projects:edit' uid=project.uid %}?next={{ request.get_full_path }}"
                    data-toggle="tooltip" title="Edit Project">
                    <i class="fas fa-pen fa-fw"></i>
                </a>
                <a class="btn btn-sm btn-danger" href="{% url 'projects:delete' uid=project.uid %}?next={{ request.get_full_path }}"
                    data-toggle="tooltip" title="Delete Project">
                    <i class="fas fa-trash fa-fw"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}