business_tracker/apps/accounts/urls.py
from django.urls import path
from apps.accounts import views

app_name = "accounts"

urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("password/reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("password/reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(), name="password_reset"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:uid>/password/change/", views.PasswordChangeView.as_view(), name="password_change"),
    path("<int:uid>/", views.DetailView.as_view(), name="detail"),
    path("<int:uid>/edit/", views.EditView.as_view(), name="edit"),
    path("<int:uid>/delete/", views.DeleteView.as_view(), name="delete"),
    path("<int:uid>/type/", views.TypeView.as_view(), name="type"),
    path("<int:uid>/activate/", views.ActivateView.as_view(), name="activate"),
    path("shifts/create/", views.CreateShiftView.as_view(), name="shifts_create"),
    path("shifts/<int:uid>/edit/", views.EditShiftView.as_view(), name="shifts_edit"),
    path("shifts/<int:uid>/delete/", views.DeleteShiftView.as_view(), name="shifts_delete"),
]

business_tracker/apps/invoices/urls.py
from django.urls import path
from apps.invoices import views

app_name = "invoices"

urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:uid>/", views.PDFView.as_view(), name="pdf"),
    path("<int:uid>/edit/", views.EditView.as_view(), name="edit"),
    path("<int:uid>/delete/", views.DeleteView.as_view(), name="delete"),
    path("<int:uid>/advance/", views.AdvanceView.as_view(), name="advance"),
]

business_tracker/apps/partners/urls.py
from django.urls import path
from apps.partners import views

app_name = "partners"

urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:uid>/", views.DetailView.as_view(), name="detail"),
    path("<int:uid>/edit/", views.EditView.as_view(), name="edit"),
    path("<int:uid>/delete/", views.DeleteView.as_view(), name="delete"),
]

business_tracker/common/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from common import views

urlpatterns = [
    path("accounts/", include("apps.accounts.urls")),
    path("invoices/", include("apps.invoices.urls")),
    path("partners/", include("apps.partners.urls")),
    path("projects/", include("apps.projects.urls")),
    path("servers/", include("apps.servers.urls")),
    path("settings/", views.SettingsView.as_view(), name="settings"),
    path("settings/dump/json/", views.DumpJsonView.as_view(), name="dump_json"),
    path("settings/dump/xml/", views.DumpXmlView.as_view(), name="dump_xml"),
    path("settings/reset/invoice/template/", views.ResetInvoiceTemplateView.as_view(), name="reset_invoice_template"),
    path("", login_required(TemplateView.as_view(template_name="dashboard.html")), name="dashboard"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

business_tracker/common/forms.py
from configparser import ConfigParser
from django import forms
from django.conf import settings


class SettingsForm(forms.Form):
    invoice_template = forms.FileField(
        required=False, label="Invoice Template", help_text="Can be left empty to keep the current template"
    )
    email_host = forms.CharField(required=False, label="Email Host", help_text="E.g. mail.novawebdevelopment.org")
    email_port = forms.IntegerField(label="Email Port")
    email_user = forms.CharField(
        required=False, label="Email User", help_text="E.g. do-not-reply@novawebdevelopment.org"
    )
    email_password = forms.CharField(required=False, label="Email Password")
    email_use_tls = forms.BooleanField(required=False, label="Use TLS for Email")
    weekly_hours = forms.IntegerField(label="Weekly Hours", help_text="Number of hours that should be tracked per week")
    overdue_days = forms.IntegerField(
        label="Overdue Days",
        help_text="Number of days after which a billed invoice is marked OVERDUE (0 = never)",
    )
    notice = forms.CharField(
        label="Notice",
        help_text="Displayed at the bottom of the invoice. Long text might be cut out depending on the invoice template",
        widget=forms.Textarea,
    )
    billing_message = forms.CharField(
        label="Billing Message",
        help_text="[contact_name] is replaced with the partner's contact name",
        widget=forms.Textarea,
    )
    auto_email = forms.BooleanField(
        required=False,
        label="Email Invoices to Partners",
        help_text="Automatically email invoices to partners when billing them",
    )
    linode_api_token = forms.CharField(required=False, label="Linode API Token", help_text="Can be left empty")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Read the config.ini file
        self.config = ConfigParser(interpolation=None)
        self.config.read(settings.CONFIG_FILE)

        # Set initial values from the config file
        self.initial["email_host"] = self.config.get("email", "EMAIL_HOST")
        self.initial["email_port"] = self.config.getint("email", "EMAIL_PORT")
        self.initial["email_user"] = self.config.get("email", "EMAIL_USER")
        self.initial["email_password"] = self.config.get("email", "EMAIL_PASSWORD")
        self.initial["email_use_tls"] = self.config.getboolean("email", "EMAIL_USE_TLS")
        self.initial["weekly_hours"] = self.config.getint("accounts", "WEEKLY_HOURS")
        self.initial["overdue_days"] = self.config.getint("invoices", "OVERDUE_DAYS")
        self.initial["notice"] = self.config.get("invoices", "NOTICE")
        self.initial["billing_message"] = self.config.get("invoices", "BILLING_MESSAGE")
        self.initial["auto_email"] = self.config.getboolean("invoices", "AUTO_EMAIL")
        self.initial["linode_api_token"] = self.config.get("servers", "LINODE_API_TOKEN")

    def clean_email_port(self):
        if not self.cleaned_data["email_port"] in range(0, 65535):
            raise forms.ValidationError("Enter an integer between 0 and 65535.")
        return self.cleaned_data["email_port"]

    def clean_weekly_hours(self):
        if self.cleaned_data["weekly_hours"] < 0:
            raise forms.ValidationError("Enter a positive integer.")
        return self.cleaned_data["weekly_hours"]

    def clean_overdue_days(self):
        if self.cleaned_data["overdue_days"] < 0:
            raise forms.ValidationError("Enter a positive integer.")
        return self.cleaned_data["overdue_days"]

    def save(self):
        self.config.set("email", "EMAIL_HOST", str(self.cleaned_data["email_host"]))
        self.config.set("email", "EMAIL_PORT", str(self.cleaned_data["email_port"]))
        self.config.set("email", "EMAIL_USER", str(self.cleaned_data["email_user"]))
        self.config.set("email", "EMAIL_PASSWORD", str(self.cleaned_data["email_password"]))
        self.config.set("email", "EMAIL_USE_TLS", str(self.cleaned_data["email_use_tls"]))
        self.config.set("accounts", "WEEKLY_HOURS", str(self.cleaned_data["weekly_hours"]))
        self.config.set("invoices", "OVERDUE_DAYS", str(self.cleaned_data["overdue_days"]))
        self.config.set("invoices", "NOTICE", str(self.cleaned_data["notice"]))
        self.config.set("invoices", "BILLING_MESSAGE", str(self.cleaned_data["billing_message"]))
        self.config.set("invoices", "AUTO_EMAIL", str(self.cleaned_data["auto_email"]))
        self.config.set("servers", "LINODE_API_TOKEN", str(self.cleaned_data["linode_api_token"]))

        with open(settings.CONFIG_FILE, "w") as f:
            self.config.write(f, space_around_delimiters=False)

business_tracker/common/views.py
import json
import os
from io import StringIO
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.management import call_command
from django.views import View
from django.contrib import messages
from django.shortcuts import render
from django.conf import settings
from common.forms import SettingsForm
from common.mixins import PermissionsRequiredMixin, NextPageMixin


class SettingsView(PermissionsRequiredMixin, View):
    superuser = True

    def get(self, request):
        form = SettingsForm()
        return render(request=request, template_name="settings.html", context={"form": form})

    def post(self, request):
        form = SettingsForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            new_template = request.FILES.get("invoice_template", None)
            if new_template:
                with open(settings.TEMPLATE_FILE, "wb+") as destination:
                    for chunk in new_template.chunks():
                        destination.write(chunk)
            messages.add_message(request, messages.SUCCESS, "The settings have been sucessfully saved.")
            form = SettingsForm()
        return render(request=request, template_name="settings.html", context={"form": form})


class DumpJsonView(PermissionsRequiredMixin, View):
    superuser = True

    def get(self, request):
        output = StringIO()
        call_command("dumpdata", format="json", exclude=["auth", "contenttypes", "sessions"], stdout=output)
        return JsonResponse(json.loads(output.getvalue()), safe=False)


class DumpXmlView(PermissionsRequiredMixin, View):
    superuser = True

    def get(self, request):
        output = StringIO()
        call_command("dumpdata", format="xml", exclude=["auth", "contenttypes", "sessions"], stdout=output)
        return HttpResponse(output.getvalue(), content_type="text/xml")


class ResetInvoiceTemplateView(PermissionsRequiredMixin, NextPageMixin, View):
    superuser = True

    def get(self, request):
        default_template = os.path.join(settings.BASE_DIR + "/apps/invoices/templates/invoices/pdfs/default_template.pdf")
        with open(default_template, "rb") as input_file:
            with open(settings.TEMPLATE_FILE, "wb+") as output_file:
                output_file.write(input_file.read())
        messages.add_message(request, messages.SUCCESS, "The invoice template have been sucessfully reset.")
        return HttpResponseRedirect(self.next)

business_tracker/common/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no">
  <title>Business Tracker</title>
  <link rel='shortcut icon' type='image/x-icon' href="{% static 'img/favicon.ico' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,500,700&display=swap">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/v/bs4/dt-1.10.23/r-2.2.7/datatables.min.css">
  <link rel="stylesheet" href="{% static 'css/business_tracker.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdn.datatables.net/v/bs4/dt-1.10.23/r-2.2.7/datatables.min.js"></script>
  <script src="{% static 'js/jquery_formset.js' %}"></script>
  <script src="{% static 'js/business_tracker.js' %}"></script>
  {% block extra_head %}{% endblock extra_head %}
</head>

<body>
  {% include "includes/sidebar.html" %}
  <div class="main">
    {% include "includes/messages.html" %}
    <h1>{% block title %}{% endblock title %}</h1>
    <p>{% block subtitle %}{% endblock subtitle %}</p>
    <hr>
    {% block content %}{% endblock content %}
  </div>
</body>

</html>

business_tracker/common/templates/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock title %}
{% block subtitle %}Access quick actions customized for your account.{% endblock subtitle %}

{% block content %}
<div class="dashboard-body core-font">
  <div class="card">
    <div class="card-body">
      <h5 class="text-uppercase m-0">Create Invoice</h5>
      <p class="mb-0">Create an invoice for your existing partners!</p>
    </div>
    <div class="card-footer w-100">
      <a class="btn btn-success btn-sm" href="{% url 'invoices:create' %}" data-toggle="tooltip" title="Create Invoice">
        <i class="fas fa-plus fa-fw"></i>
      </a>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <h5 class="text-uppercase m-0">Create Partner</h5>
      <p class="mb-0">Create a new partner!</p>
    </div>
    <div class="card-footer w-100">
      <a class="btn btn-success btn-sm" href="{% url 'partners:create' %}" data-toggle="tooltip" title="Create Partner">
        <i class="fas fa-plus fa-fw"></i>
      </a>
    </div>
  </div>
  {% for shift in shifts %}
  <div class="card">
    <div class="card-body">
      <h5 class="text-uppercase m-0">Shift <span class="text-secondary">{{ shift.description|truncatechars:32 }}</span></h5>
      <p class="text-danger">Not associated with any project</p>
      <p class="mb-0">
        Date: <span class="text-secondary">{{ shift.date }}</span><br>
        Duration: <span class="text-secondary">{{ shift }}</span><br>
        Project: <span class="text-secondary">{{ invoice.project.name|default:"N/A" }}</span>
      </p>
    </div>
    <div class="card-footer w-100">
      <a class="btn btn-warning btn-sm" href="{% url 'accounts:shifts_edit' uid=shift.uid %}" data-toggle="tooltip" title="Edit Shift">
        <i class="fas fa-pen fa-fw"></i>
      </a>
      <a class="btn btn-danger btn-sm" href="{% url 'accounts:shifts_delete' uid=shift.uid %}" data-toggle="tooltip" title="Delete Shift">
        <i class="fas fa-trash fa-fw"></i>
      </a>
    </div>
  </div>
  {% endfor %}
  {% for invoice in invoices %}
  <div class="card">
    <div class="card-body">
      <h5 class="text-uppercase m-0">Invoice <span class="text-secondary">{{ invoice.invoice_id }}</span></h5>
      <p>{{ invoice.get_html_status }}</p>
      <p class="mb-0">
        Partner: <span class="text-secondary">{{ invoice.partner.company }}</span><br>
        Amount: <span class="text-secondary">${{ invoice.get_total }}</span><br>
        Bill Date: <span class="text-secondary">{{ invoice.bill_date|default:"N/A" }}</span>
      </p>
    </div>
    <div class="card-footer w-100">
      <a class="btn btn-info btn-sm" href="{% url 'invoices:pdf' uid=invoice.uid %}" target="_blank" data-toggle="tooltip"
        title="View Invoice">
        <i class="fas fa-file-pdf fa-fw"></i>
      </a>
      <a class="btn btn-primary btn-sm advance-invoice" href="{% url 'invoices:advance' uid=invoice.uid %}" data-toggle="tooltip"
        title="Advance Invoice Status">
        <i class="fas fa-step-forward fa-fw"></i>
      </a>
      <a class="btn btn-warning btn-sm" href="{% url 'invoices:edit' uid=invoice.uid %}" data-toggle="tooltip" title="Edit Invoice">
        <i class="fas fa-pen fa-fw"></i>
      </a>
      <a class="btn btn-danger btn-sm" href="{% url 'invoices:delete' uid=invoice.uid %}" data-toggle="tooltip" title="Delete Invoice">
        <i class="fas fa-trash fa-fw"></i>
      </a>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}

business_tracker/common/templates/email.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>

<head>
  <title>
  </title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <style type="text/css">
    body {
      background-color: #FFFFFF;
      width: 100%;
      padding: 0;
      margin: 0;
    }

    #main {
      width: 100%;
      padding: 0;
      margin: 0;
    }

    #header {
      margin: 0;
      padding: 16px 0 16px;
      font-family: 'Arial', sans-serif;
      font-weight: 700;
      font-size: 32px;
      color: #000000;
      text-align: center;
      border-bottom: 4px solid #202020;
    }

    #message {
      padding: 0;
      margin: 128px auto 128px;
      width: 480px;
      font-family: 'Arial', sans-serif;
      font-weight: 700;
      font-size: 48px;
      color: #000000;
      text-align: center;
    }

    #message>p {
      margin: 0 0 64px;
      padding: 0
    }

    #message>a {
      margin: 0;
      padding: 0;
      font-size: 24px;
      text-decoration: none;
    }

    .footer {
      padding: 8px;
      border-top: 4px solid #202020;
      background: #000000;
      color: #808080;
      font-family: Arial;
      text-transform: uppercase;
      font-weight: 500
    }

    .footer p {
      margin: 8px;
      font-size: 8px;
      text-align: center;
    }

    .footer a {
      font-size: 12px;
      text-align: center;
      text-decoration: none;
    }

    .footer-logos {
      text-align: center;
    }
  </style>
</head>

<body>
  <div id="main">
    <div>
      <h1 id="header">Business Tracker</h1>
    </div>
    <div id="message">
      <p>{{ message }}</p>
      <a href="{{ url }}">{{ button }}</a>
    </div>
    <div class="footer footer-logos">
      <p>Copyright &copy; 2020</p>
      <a href="https://novawebdevelopment.com/">NOVA Web Development</a>
    </div>
  </div>
</body>

</html>

business_tracker/common/templates/settings.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block extra_head %}
<script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.min.js"></script>
{% endblock extra_head %}

{% block title %}Settings{% endblock title %}
{% block subtitle %}Set up Business Tracker the way you want.{% endblock subtitle %}

{% block content %}
<form novalidate enctype="multipart/form-data" method="post">
  {% csrf_token %}
  <div id="div_{{ form.invoice_template.id_for_label }}" class="form-group">
    <label for="{{ form.invoice_template.id_for_label }}">{{ form.invoice_template.label }}</label>
    <div class="custom-file">
      <input type="file" name="{{ form.invoice_template.name }}" class="custom-file-input" id="{{ form.invoice_template.id_for_label }}"
        accept="application/pdf">
      <label class="custom-file-label" for="{{ form.invoice_template.id_for_label }}">Choose PDF file</label>
      {% if form.invoice_template.help_text %}
      <small id="hint_{{ form.invoice_template.name }}" class="form-text text-muted">{{ form.invoice_template.help_text }}</small>
      {% endif %}
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-12 col-xl-6">
      {{ form.email_host|as_crispy_field }}
    </div>
    <div class="col-12 col-xl-6">
      {{ form.email_port|as_crispy_field }}
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-xl-6">
      {{ form.email_user|as_crispy_field }}
    </div>
    <div class="col-12 col-xl-6">
      <div id="div_id_email_password" class="form-group">
        <label for="id_email_password" class="">
          Email Password
        </label>
        <div class="">
          <div class="input-group mb-3">
            <input type="password" name="email_password" value="{{ form.email_password.value }}" class="textinput textInput form-control"
              id="id_email_password">
            <div class="input-group-append">
              <button type="button" id="emailPasswordButton" class="btn btn-outline-info" data-toggle="button" id="emailPasswordButton">
                <i class="fas fa-eye fa-fw"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div id="div_{{ form.email_use_tls.id_for_label }}" class="custom-control custom-checkbox">
      <input type="checkbox" class="custom-control-input" name="{{ form.email_use_tls.name }}" id="{{ form.email_use_tls.id_for_label }}"
      {% if form.email_use_tls.value %} checked {% endif %}>
      <label class="custom-control-label" for="{{ form.email_use_tls.id_for_label }}">{{ form.email_use_tls.label }}</label>
      {% if form.email_use_tls.help_text %}
      <small id="hint_{{ form.email_use_tls.name }}" class="form-text text-muted">{{ form.email_use_tls.help_text }}</small>
      {% endif %}
    </div>
  </div>
  <hr>
  {{ form.weekly_hours|as_crispy_field }}
  {{ form.overdue_days|as_crispy_field }}
  {{ form.notice|as_crispy_field }}
  {{ form.billing_message|as_crispy_field }}
  <div class="form-group">
    <div id="div_{{ form.auto_email.id_for_label }}" class="custom-control custom-checkbox">
      <input type="checkbox" class="custom-control-input" name="{{ form.auto_email.name }}" id="{{ form.auto_email.id_for_label }}"
      {% if form.auto_email.value %} checked {% endif %}>
      <label class="custom-control-label" for="{{ form.auto_email.id_for_label }}">{{ form.auto_email.label }}</label>
      {% if form.auto_email.help_text %}
      <small id="hint_{{ form.auto_email.name }}" class="form-text text-muted">{{ form.auto_email.help_text }}</small>
      {% endif %}
    </div>
  </div>
  <hr>
  {{ form.linode_api_token|as_crispy_field }}
  <hr>
  <div class="form-actions">
    <button type="submit" class="btn btn-success btn-detail">
      <i class="fas fa-check fa-fw mr-1"></i>
      Save
    </button>
    <a class="btn btn-primary btn-detail" href="{% url 'dump_json' %}">
      <i class="fas fa-save fa-fw mr-1"></i>
      Dump JSON
    </a>
    <a class="btn btn-primary btn-detail" href="{% url 'dump_xml' %}">
      <i class="fas fa-save fa-fw mr-1"></i>
      Dump XML
    </a>
    <a class="btn btn-danger btn-detail" href="{% url 'reset_invoice_template' %}?next={{ request.get_full_path }}">
      <i class="fas fa-undo-alt fa-fw mr-1"></i>
      Reset Invoice Template
    </a>
  </div>
</form>
<script>
  $(document).ready(function () {
    bsCustomFileInput.init()
  })
</script>
{% endblock content %}