business_tracker/apps/accounts/urls.py
from django.urls import path
from apps.accounts import views

app_name = "accounts"

urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("password/reset/", views.PasswordResetView.as_view(), name="password_reset"),
    path("password/reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(), name="password_reset"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:uid>/password/change/", views.PasswordChangeView.as_view(), name="password_change"),
    path("<int:uid>/", views.DetailView.as_view(), name="detail"),
    path("<int:uid>/edit/", views.EditView.as_view(), name="edit"),
    path("<int:uid>/delete/", views.DeleteView.as_view(), name="delete"),
    path("<int:uid>/type/", views.TypeView.as_view(), name="type"),
    path("<int:uid>/activate/", views.ActivateView.as_view(), name="activate"),
    path("shifts/create/", views.CreateShiftView.as_view(), name="shifts_create"),
    path("shifts/<int:uid>/edit/", views.EditShiftView.as_view(), name="shifts_edit"),
    path("shifts/<int:uid>/delete/", views.DeleteShiftView.as_view(), name="shifts_delete"),
]

business_tracker/apps/projects/urls.py
from django.urls import path
from apps.projects import views

app_name = "projects"

urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:uid>/", views.DetailView.as_view(), name="detail"),
    path("<int:uid>/edit/", views.EditView.as_view(), name="edit"),
    path("<int:uid>/delete/", views.DeleteView.as_view(), name="delete"),
    path("<int:uid>/generate/ros/", views.GenerateROSView.as_view(), name="generate_ros"),
]

business_tracker/common/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from common import views

urlpatterns = [
    path("accounts/", include("apps.accounts.urls")),
    path("invoices/", include("apps.invoices.urls")),
    path("partners/", include("apps.partners.urls")),
    path("projects/", include("apps.projects.urls")),
    path("servers/", include("apps.servers.urls")),
    path("settings/", views.SettingsView.as_view(), name="settings"),
    path("settings/dump/json/", views.DumpJsonView.as_view(), name="dump_json"),
    path("settings/dump/xml/", views.DumpXmlView.as_view(), name="dump_xml"),
    path("settings/reset/invoice/template/", views.ResetInvoiceTemplateView.as_view(), name="reset_invoice_template"),
    path("", login_required(TemplateView.as_view(template_name="dashboard.html")), name="dashboard"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

business_tracker/apps/accounts/models.py
from django_countries.fields import CountryField
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from apps.accounts.managers import AccountManager
from apps.projects.models import Project


class Account(AbstractBaseUser):
    uid = models.AutoField(primary_key=True)
    email = models.EmailField(unique=True, error_messages={"unique": "This email is already in use."})
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)

    address1 = models.CharField(max_length=48, blank=True, help_text="Street address, P.O. box")
    address2 = models.CharField(max_length=32, blank=True, help_text="Apartment, suite, unit, building, floor")
    city = models.CharField(max_length=32, blank=True)
    state = models.CharField(max_length=32, blank=True, help_text="Should use 2 letter abbreviations for U.S. states")
    zipcode = models.CharField(max_length=16, blank=True)
    country = CountryField(blank_label="", blank=True)

    is_superuser = models.BooleanField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = AccountManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    class Meta:
        ordering = ["first_name"]

    def __str__(self):
        return self.get_full_name()

    @property
    def _can_delete(self):
        return not bool(self.shifts.exclude(project=None))

    def get_full_name(self):
        return self.first_name + " " + self.last_name


class Shift(models.Model):
    uid = models.AutoField(primary_key=True)
    description = models.CharField(max_length=128)
    duration = models.IntegerField()
    date = models.DateField()
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name="shifts", null=True, blank=True)
    worker = models.ForeignKey(Account, on_delete=models.CASCADE, related_name="shifts")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        hours = self.duration // 3600
        minutes = self.duration % 3600 // 60
        return f"{hours:02d}:{minutes:02d}"

    class Meta:
        ordering = ["-date", "-created_at"]

business_tracker/apps/accounts/views.py
from configparser import ConfigParser
from datetime import datetime, timedelta
from django.views import View
from django.conf import settings
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.shortcuts import render
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from common.mixins import AccessModelMixin, PermissionsRequiredMixin, NextPageMixin
from apps.accounts.models import Account, Shift
from apps.accounts.forms import *


class LoginView(View):
    def dispatch(self, request):
        self.next = request.GET.get("next", None)
        if not self.next or "://" in self.next or " " in self.next:
            self.next = "/"
        if request.user.is_authenticated:
            messages.add_message(request, messages.WARNING, "You are already logged in!")
            return HttpResponseRedirect(self.next)
        return super().dispatch(request)

    def get(self, request):
        form = LoginForm()
        return render(request=request, template_name="accounts/login.html", context={"form": form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.login(request):
            messages.add_message(
                request, messages.SUCCESS, f"Welcome back, {request.user.first_name}! You have successfully logged in."
            )
            return HttpResponseRedirect(self.next)
        return render(request=request, template_name="accounts/login.html", context={"form": form})


class LogoutView(View):
    def get(self, request):
        if request.user.is_authenticated:
            logout(request)
            messages.add_message(request, messages.SUCCESS, "You have successfully logged out.")
        else:
            messages.add_message(request, messages.WARNING, "You are already logged out!")
        return HttpResponseRedirect(reverse("accounts:login"))


class PasswordResetView(View):
    def dispatch(self, request):
        if request.user.is_authenticated:
            messages.add_message(
                request,
                messages.WARNING,
                "You have been redirected to change your password because you are logged in!",
            )
            return HttpResponseRedirect(reverse("accounts:password_change", args={request.user.uid}))
        return super().dispatch(request)

    def get(self, request):
        form = PasswordResetForm()
        return render(request=request, template_name="accounts/password/reset.html", context={"form": form})

    def post(self, request):
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            if form.save(request=request):
                messages.add_message(request, messages.SUCCESS, "You have successfully requested a password reset.")
            else:
                messages.add_message(request, messages.ERROR, "The settings for sending email are not valid.")
            return HttpResponseRedirect(reverse("accounts:login"))
        return render(request=request, template_name="accounts/password/reset.html", context={"form": form})


class PasswordResetConfirmView(View):
    def dispatch(self, request, uidb64, token):
        if request.user.is_authenticated:
            messages.add_message(
                request,
                messages.WARNING,
                "You have been redirected to change your password because you are logged in!",
            )
            return HttpResponseRedirect(reverse("accounts:password_change", args={request.user.uid}))
        try:
            self.account = Account.objects.get(uid=force_text(urlsafe_base64_decode(uidb64)))
            if default_token_generator.check_token(self.account, token):
                return super().dispatch(request)
            raise Account.DoesNotExist
        except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
            messages.add_message(request, messages.ERROR, "The password reset request is not valid.")
            return HttpResponseRedirect(reverse("accounts:password_reset"))

    def get(self, request):
        form = PasswordResetConfirmForm()
        return render(request=request, template_name="accounts/password/set.html", context={"form": form})

    def post(self, request):
        form = PasswordResetConfirmForm(request.POST)
        if form.is_valid():
            form.save(account=self.account)
            messages.add_message(request, messages.SUCCESS, "You have successfully set your password.")
            return HttpResponseRedirect(reverse("accounts:login"))
        return render(request=request, template_name="accounts/password/set.html", context={"form": form})


class PasswordChangeView(PermissionsRequiredMixin, AccessModelMixin, View):
    personal = True
    model = Account

    def get(self, request):
        form = PasswordChangeForm()
        return render(request=request, template_name="accounts/password/change.html", context={"form": form})

    def post(self, request):
        form = PasswordChangeForm(request.POST)
        if form.is_valid():
            form.save(self.account)
            messages.add_message(request, messages.SUCCESS, "You have successfully changed your password.")
            return HttpResponseRedirect(reverse("accounts:login"))
        return render(request=request, template_name="accounts/password/change.html", context={"form": form})


class ActivateView(PermissionsRequiredMixin, AccessModelMixin, NextPageMixin, View):
    superuser = True
    model = Account

    def get(self, request):
        form = AccountForm(instance=self.account)
        if form.send_activation_email(account=self.account, request=request):
            messages.add_message(request, messages.SUCCESS, "The activation email has been successfully sent.")
        else:
            messages.add_message(request, messages.ERROR, "The activation email could not be sent.")
        return HttpResponseRedirect(self.next)


class ListView(PermissionsRequiredMixin, View):
    superuser = True

    def get(self, request):
        accounts = Account.objects.all()
        return render(request=request, template_name="accounts/list.html", context={"accounts": accounts})


class CreateView(PermissionsRequiredMixin, NextPageMixin, View):
    superuser = True

    def get(self, request):
        form = AccountForm()
        return render(request=request, template_name="accounts/create.html", context={"form": form})

    def post(self, request):
        form = AccountForm(request.POST)
        if form.is_valid():
            if form.send_activation_email(account=form.save(), request=request):
                messages.add_message(request, messages.SUCCESS, "The account has been successfully created.")
            else:
                messages.add_message(
                    request,
                    messages.WARNING,
                    "The account has been created, but an activation email could not be sent.",
                )
            return HttpResponseRedirect(self.next)
        return render(request=request, template_name="accounts/create.html", context={"form": form})


class DetailView(PermissionsRequiredMixin, AccessModelMixin, View):
    personal = True
    superuser = True
    model = Account

    def get(self, request):
        last_sunday = datetime.date.today() - datetime.timedelta(days=datetime.date.today().weekday() + 1)
        hours_worked = 0
        for shift in self.account.shifts.filter(date__gte=last_sunday):
            hours_worked += shift.duration

        config = ConfigParser(interpolation=None)
        config.read(settings.CONFIG_FILE)

        percentage = hours_worked / (config.getint("accounts", "WEEKLY_HOURS") * 3600)
        hours_worked = int(hours_worked / 3600)

        if percentage != 0:
            background_size = max((1 / percentage) * 100, 100)
        else:
            background_size = 0

        return render(
            request=request,
            template_name="accounts/detail.html",
            context={
                "account": self.account,
                "percentage": f"{int(percentage * 100)}",
                "hours_worked": f'{hours_worked}/{config.getint("accounts", "WEEKLY_HOURS")}',
                "background_size": background_size,
            },
        )


class EditView(PermissionsRequiredMixin, NextPageMixin, AccessModelMixin, View):
    personal = True
    superuser = True
    model = Account

    def get(self, request):
        form = AccountForm(instance=self.account, initial={"verify_email": self.account.email})
        return render(request=request, template_name="accounts/edit.html", context={"form": form})

    def post(self, request):
        form = AccountForm(request.POST, instance=self.account)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, "The account has been successfully edited.")
            return HttpResponseRedirect(self.next)
        print([error for error in form.non_field_errors()])
        return render(request=request, template_name="accounts/edit.html", context={"form": form})


class DeleteView(PermissionsRequiredMixin, NextPageMixin, AccessModelMixin, View):
    personal = True
    superuser = True
    model = Account

    def get(self, request):
        return render(
            request=request, template_name="accounts/delete.html", context={"can_delete": self.account._can_delete}
        )

    def post(self, request):
        if self.account._can_delete:
            self.account.delete()
            messages.add_message(request, messages.SUCCESS, "The account has been deleted.")
        else:
            messages.add_message(
                request, messages.ERROR, "There are one or more shifts that have an associated project."
            )

business_tracker/apps/accounts/templates/accounts/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create Account{% endblock title %}
{% block subtitle %}Create a new account.{% endblock subtitle %}

{% block content %}
<form novalidate method="post">
  {% csrf_token %}
  {% if form.non_field_errors %}
  <div class="alert alert-block alert-danger">
    <ul class="m-0">
      {{ form.non_field_errors|unordered_list }}
    </ul>
  </div>
  {% endif %}
  <div class="row">
    <div class="col-12 col-xl-6">
      {{ form.email|as_crispy_field }}
    </div>
    <div class="col-12 col-xl-6">
      {{ form.verify_email|as_crispy_field }}
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-12 col-xl-6">
      {{ form.first_name|as_crispy_field }}
    </div>
    <div class="col-12 col-xl-6">
      {{ form.last_name|as_crispy_field }}
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-12 col-xl-6">
      {{ form.address1|as_crispy_field }}
    </div>
    <div class="col-12 col-xl-6">
      {{ form.address2|as_crispy_field }}
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-xl-6">
      {{ form.city|as_crispy_field }}
    </div>
    <div class="col-12 col-xl-6">
      {{ form.state|as_crispy_field }}
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-xl-6">
      {{ form.zipcode|as_crispy_field }}
    </div>
    <div class="col-12 col-xl-6">
      {{ form.country|as_crispy_field }}
    </div>
  </div>
  <hr>
  <div class="form-group">
    <p>The new user will receive an email with instructions on how to activate their account.</p>
  </div>
  <hr>
  <div class="form-actions">
    <button type="submit" class="btn btn-success btn-detail">
      <i class="fas fa-check fa-fw mr-1"></i>
      Save
    </button>
    <a class="btn btn-secondary btn-detail" href="{{ request.GET.next }}">
      <i class="fas fa-times-circle fa-fw mr-1"></i>
      Cancel
    </a>
  </div>
</form>
{% endblock content %}

business_tracker/apps/accounts/templates/accounts/delete.html
{% extends "base.html" %}

{% block title %}Delete Account{% endblock title %}
{% block subtitle %}Delete the account and associated data.{% endblock subtitle %}

{% block content %}
<form novalidate method="post">
  {% csrf_token %}
  <div class="form-group">
    {% if can_delete %}
    <p>
      Are you sure you want to proceed?
      <br>
      This action is <span class="text-danger">irreversible</span>.
    </p>
    {% else %}
    <p>
      The account <span class="text-danger">cannot</span> be deleted.
      <br>
      There are one or more shifts that have an associated project.
    </p>
    {% endif %}
  </div>
  <hr>
  <div class="form-actions">
    {% if can_delete %}
    <button type="submit" class="btn btn-danger btn-detail">
      <i class="fas fa-trash fa-fw mr-1"></i>
      Delete
    </button>
    {% endif %}
    <a class="btn btn-secondary btn-detail" href="{% firstof request.GET.cancel request.GET.next %}">
      <i class="fas fa-times-circle fa-fw mr-1"></i>
      Cancel
    </a>
  </div>
</form>
{% endblock content %}

business_tracker/apps/accounts/templates/accounts/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ account.get_full_name }}{% endblock title %}
{% block subtitle %}View details about the account.{% endblock subtitle %}

{% block content %}
<div class="container-fluid no-gutters">
  <div class="row pt-3">
    <div class="col-xl-6 px-0 pr-xl-3">
      <h2>Account Information</h2>
      <table class="table">
        <tbody>
          <tr>
            <th scope="row">Type</th>
            <td>{{ account.is_superuser|yesno:"Manager,Developer" }}</td>
          </tr>
          <tr>
            <th scope="row">First Name</th>
            <td>{{ account.first_name }}</td>
          </tr>
          <tr>
            <th scope="row">Last Name</th>
            <td>{{ account.last_name }}</td>
          </tr>
          <tr>
            <th scope="row">Email</th>
            <td><a href="mailto:{{ account.email }}" style="word-break:break-all;">{{ account.email }}</a></td>
          </tr>
          <tr>
            <th scope="row">Address Line 1</th>
            <td>{{ account.address1 }}</td>
          </tr>
          <tr>
            <th scope="row">Address Line 2</th>
            <td>{{ account.address2 }}</td>
          </tr>
          <tr>
            <th scope="row">City</th>
            <td>{{ account.city }}</td>
          </tr>
          <tr>
            <th scope="row">State / Region / Province</th>
            <td>{{ account.state }}</td>
          </tr>
          <tr>
            <th scope="row">ZIP / Postal Code</th>
            <td>{{ account.zipcode }}</td>
          </tr>
          <tr>
            <th scope="row">Country</th>
            <td>{{ account.country.name }} <img src="{{ account.country.flag }}"></td>
          </tr>
          <tr>
            <th scope="row">Last Login</th>
            <td>{{ account.last_login }}</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-xl-6 px-0 pl-xl-3">
      <h2>Work Shifts</h2>
      <div class="progress mb-2">
        <div class="progress-bar progress-time-track" role="progressbar"
          style="width: {{ percentage }}%; background-size: {{ background_size }}%;">
        </div>
        <p class="justify-content-center d-flex position-absolute w-100">
          Weekly Progress: {{ percentage }}% ({{ hours_worked }})
        </p>
      </div>
      <table id="jsDetailTable" class="table table-sm nowrap" style="width: 100%;">
        <thead>
          <tr>
            <th scope="col">Description</th>
            <th scope="col">Duration</th>
            <th scope="col">Date</th>
            <th scope="col">Project</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          {% for shift in account.shifts.all %}
          <tr>
            <td data-toggle="tooltip" title="{{ shift.description }}">{{ shift.description|truncatechars:16 }}</td>
            <td>{{ shift }}</td>
            <td>{{ shift.date }}</td>
            <td>
              {% if shift.project %}
              <a href="{% url 'projects:detail' uid=shift.project.uid %}">{{ shift.project }}</a>
              {% else %}
              N/A
              {% endif %}
            </td>
            <td>
              {% if request.user.uid == account.uid %}
              <a class="btn btn-sm btn-warning" href="{% url 'accounts:shifts_edit' uid=shift.uid %}?next={{ request.get_full_path }}"
                data-toggle="tooltip" title="Edit Shift">
                <i class="fas fa-pen fa-fw"></i>
              </a>
              <a class="btn btn-sm btn-danger" href="{% url 'accounts:shifts_delete' uid=shift.uid %}?next={{ request.get_full_path }}"
                data-toggle="tooltip" title="Delete Shift">
                <i class="fas fa-trash fa-fw"></i>
              </a>
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
<hr>
<div class="container-fluid no-gutters">
  <div class="row">
    {% if request.user.is_superuser %}
    {% if not request.GET.personal %}
    <a class="btn btn-dark btn-detail" href="{% url 'accounts:list' %}">
      <i class="fas fa-arrow-left"></i>
    </a>
    {% endif %}
    {% if not account.password %}
    <a class="btn btn-info btn-detail mx-2" href="{% url 'accounts:activate' uid=account.uid %}?next={{ request.get_full_path }}">
      <i class="fas fa-share fa-fw mr-1"></i>
      Resend Activation Email
    </a>
    {% endif %}
    {% if account.is_superuser %}
    <a class="btn btn-primary btn-detail mx-2" href="{% url 'accounts:type' uid=account.uid %}?next={{ request.get_full_path }}">
      <i class="fas fa-sync-alt fa-fw mr-1"></i>
      Demote to Developer
    </a>
    {% else %}
    <a class="btn btn-primary btn-detail mx-2" href="{% url 'accounts:type' uid=account.uid %}?next={{ request.get_full_path }}">
      <i class="fas fa-sync-alt fa-fw mr-1"></i>
      Promote to Manager
    </a>
    {% endif %}
    {% endif %}
    {% if request.user.uid == account.uid %}
    <a class="btn btn-secondary btn-detail mx-2"
      href="{% url 'accounts:password_change' uid=account.uid %}?next={{ request.get_full_path }}">
      <i class="fas fa-key fa-fw mr-1"></i>
      Change Password
    </a>
    {% endif %}
    <a class="btn btn-warning btn-detail mx-2" href="{% url 'accounts:edit' uid=account.uid %}?next={{ request.get_full_path }}">
      <i class="fas fa-pen fa-fw mr-1"></i>
      Edit Account
    </a>
    <a class="btn btn-danger btn-detail mx-2"
      href="{% url 'accounts:delete' uid=account.uid %}?next=/accounts/&cancel={{ request.get_full_path }}">
      <i class="fas fa-trash fa-fw mr-1"></i>
      Delete Account
    </a>
  </div>
</div>
<script>
  table = $('#jsDetailTable').DataTable({
    responsive: true,
    dom: '<"row no-gutters flex-nowrap"<"flex-grow-1"f><"flex-shrink-0 ml-1"p>>t',
    pagingType: "numbers",
    pageLength: 10,
    ordering: false,
    language: {
      lengthMenu: "_MENU_",
      search: "_INPUT_",
      searchPlaceholder: "Search"
    },
    columnDefs: [
      {
        targets: [0, -1],
        responsivePriority: 1
      }]
  });
  $('#jsDetailTable_filter').removeClass('dataTables_filter');
  $('#jsDetailTable_filter > label').contents().unwrap();
</script>
{% endblock content %}

business_tracker/apps/accounts/templates/accounts/edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Edit Account{% endblock title %}
{% block subtitle %}Edit the account.{% endblock subtitle %}

{% block content %}
<form novalidate method="post">
  {% csrf_token %}
  {% if form.non_field_errors %}
  <div class="alert alert-block alert-danger">
    <ul class="m-0">
      {{ form.non_field_errors|unordered_list }}
    </ul>
  </div>
  {% endif %}
  <div class="row">
    <div class="col-12 col-xl-6">
      {{ form.email|as_crispy_field }}
    </div>
    <div class="col-12 col-xl-6">
      {{ form.verify_email|as_crispy_field }}
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-12 col-xl-6">
      {{ form.first_name|as_crispy_field }}
    </div>
    <div class="col-12 col-xl-6">
      {{ form.last_name|as_crispy_field }}
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-12 col-xl-6">
      {{ form.address1|as_crispy_field }}
    </div>
    <div class="col-12 col-xl-6">
      {{ form.address2|as_crispy_field }}
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-xl-6">
      {{ form.city|as_crispy_field }}
    </div>
    <div class="col-12 col-xl-6">
      {{ form.state|as_crispy_field }}
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-xl-6">
      {{ form.zipcode|as_crispy_field }}
    </div>
    <div class="col-12 col-xl-6">
      {{ form.country|as_crispy_field }}
    </div>
  </div>
  <hr>
  <div class="form-actions">
    <button type="submit" class="btn btn-success btn-detail">
      <i class="fas fa-check fa-fw mr-1"></i>
      Save
    </button>
    <a class="btn btn-secondary btn-detail" href="{{ request.GET.next }}">
      <i class="fas fa-times-circle fa-fw mr-1"></i>
      Cancel
    </a>
  </div>
</form>
{% endblock content %}

business_tracker/apps/accounts/templates/accounts/list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Accounts{% endblock title %}
{% block subtitle %}View the list of all accounts.{% endblock subtitle %}

{% block content %}
<table id="jsTable" class="table list-view nowrap" style="width: 100%;">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Type</th>
      <th scope="col">
        <a class="btn btn-sm btn-success" href="{% url 'accounts:create' %}?next={{ request.get_full_path }}">
          <i class="fas fa-plus fa-fw"></i>
          Create Account
        </a>
      </th>
    </tr>
  </thead>
  <tbody>
    {% for account in accounts %}
    <tr>
      <td>{{ account.first_name }}</td>
      <td>{{ account.last_name }}</td>
      <td><a href="mailto:{{ account.email }}">{{ account.email }}</a></td>
      <td>{{ account.is_superuser|yesno:"Manager,Developer" }}</td>
      <td>
        <a class="btn btn-sm btn-info" href="{% url 'accounts:detail' uid=account.uid %}" data-toggle="tooltip" title="View Account">
          <i class="fas fa-eye fa-fw"></i>
        </a>
        <a class="btn btn-sm btn-warning" href="{% url 'accounts:edit' uid=account.uid %}?next={{ request.get_full_path }}"
          data-toggle="tooltip" title="Edit Account">
          <i class="fas fa-pen fa-fw"></i>
        </a>
        <a class="btn btn-sm btn-danger" href="{% url 'accounts:delete' uid=account.uid %}?next={{ request.get_full_path }}"
          data-toggle="tooltip" title="Delete Account">
          <i class="fas fa-trash fa-fw"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

business_tracker/apps/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Login{% endblock title %}
{% block subtitle %}All users need to be logged in due to the presence of confidential information.{% endblock subtitle %}

{% block content %}
<form novalidate method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <hr>
  <div class="form-actions">
    <button type="submit" class="btn btn-primary btn-detail">
      <i class="fas fa-sign-in-alt fa-fw mr-1"></i>
      Log in
    </button>
  </div>
</form>
{% endblock content %}