business_tracker/apps/servers/urls.py
from django.urls import path
from apps.servers import views

app_name = "servers"

urlpatterns = [
    path("", views.ListView.as_view(), name="list"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:uid>/", views.DetailView.as_view(), name="detail"),
    path("<int:uid>/edit/", views.EditView.as_view(), name="edit"),
    path("<int:uid>/delete/", views.DeleteView.as_view(), name="delete"),
]

business_tracker/common/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from common import views

urlpatterns = [
    path("accounts/", include("apps.accounts.urls")),
    path("invoices/", include("apps.invoices.urls")),
    path("partners/", include("apps.partners.urls")),
    path("projects/", include("apps.projects.urls")),
    path("servers/", include("apps.servers.urls")),
    path("settings/", views.SettingsView.as_view(), name="settings"),
    path("settings/dump/json/", views.DumpJsonView.as_view(), name="dump_json"),
    path("settings/dump/xml/", views.DumpXmlView.as_view(), name="dump_xml"),
    path("settings/reset/invoice/template/", views.ResetInvoiceTemplateView.as_view(), name="reset_invoice_template"),
    path("", login_required(TemplateView.as_view(template_name="dashboard.html")), name="dashboard"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

business_tracker/apps/servers/models.py
from decimal import Decimal
from django.db import models


class Server(models.Model):
    LINODE = 0
    OTHER = 9

    HOSTING_PROVIDERS = ((LINODE, "Linode"), (OTHER, "Other"))

    uid = models.AutoField(primary_key=True)
    hosting_provider = models.PositiveSmallIntegerField()
    provider_id = models.CharField(max_length=255, blank=False)

    label = models.CharField(max_length=64, blank=False)
    operating_system = models.CharField(max_length=32, blank=False)
    specifications = models.TextField(blank=False)
    ip_address = models.CharField(max_length=40, blank=False)
    root_password = models.CharField(max_length=64)
    price = models.CharField(max_length=16, blank=False)

    status = models.CharField(max_length=32, blank=False, default="N/A")
    region = models.CharField(max_length=32, blank=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_hosting_provider(self):
        return dict(self.HOSTING_PROVIDERS).get(self.hosting_provider)


class Service(models.Model):
    uid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=32)
    platform = models.CharField(max_length=32)
    url = models.URLField()
    server = models.ForeignKey(Server, related_name="services", on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["created_at"]

business_tracker/apps/servers/forms.py
from django import forms
from django.conf import settings
from apps.servers import apis
from apps.servers.models import Server, Service


class ServerForm(forms.ModelForm):
    hosting_provider = forms.ChoiceField(choices=apis.get_hosting_providers)

    class Meta:
        model = Server
        exclude = ("status",)
        labels = {
            "hosting_provider": "Hosting Provider",
            "provider_id": "Provider ID",
            "operating_system": "Operating System",
            "ip_address": "IP Address",
            "root_password": "Root Password",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance = getattr(self, "instance", None)
        fields_to_del = set()

        if self.instance and self.instance.pk:
            self.fields["hosting_provider"].disabled = True
            self.fields["provider_id"].disabled = True
            if self.instance.hosting_provider == Server.OTHER:
                fields_to_del.add("provider_id")
            else:
                fields_to_del.add("label")
                fields_to_del.add("operating_system")
                fields_to_del.add("specifications")
                fields_to_del.add("ip_address")
                fields_to_del.add("price")
                fields_to_del.add("region")
        elif self.data.get("hosting_provider", None):
            if int(self.data.get("hosting_provider", None)) == Server.OTHER:
                self.fields["provider_id"].required = False
            else:
                self.fields["label"].required = False
                self.fields["operating_system"].required = False
                self.fields["specifications"].required = False
                self.fields["ip_address"].required = False
                self.fields["price"].required = False
                self.fields["region"].required = False

        for field in fields_to_del:
            del self.fields[field]

    def clean(self):
        self.cleaned_data = super().clean()
        if self.errors:
            return
        if int(self.cleaned_data["hosting_provider"]) == Server.OTHER:
            self.cleaned_data["provider_id"] = ""
        if not apis.is_server_id_valid(self.cleaned_data["provider_id"], int(self.cleaned_data["hosting_provider"])):
            raise forms.ValidationError("The Provider ID is not valid.")
        return self.cleaned_data


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = "__all__"

business_tracker/apps/servers/views.py
from django.views import View
from django.shortcuts import render, reverse
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.forms import inlineformset_factory
from common.mixins import AccessModelMixin, PermissionsRequiredMixin, NextPageMixin
from apps.servers import apis
from apps.servers.models import Server, Service
from apps.servers.forms import ServerForm, ServiceForm


class ListView(PermissionsRequiredMixin, View):
    def get(self, request):
        servers = Server.objects.all()
        for server in servers:
            server.status_color = apis.get_status_color(server)
        return render(request=request, template_name="servers/list.html", context={"servers": servers})


class CreateView(PermissionsRequiredMixin, NextPageMixin, View):
    superuser = True

    def get(self, request):
        form = ServerForm()
        ServicesFormSet = inlineformset_factory(Server, Service, fields="__all__", extra=1)
        formset = ServicesFormSet()
        return render(request=request, template_name="servers/create.html", context={"form": form, "formset": formset})

    def post(self, request):
        form = ServerForm(request.POST)
        ServicesFormSet = inlineformset_factory(Server, Service, fields="__all__", extra=0)
        if form.is_valid():
            server = form.save(commit=False)
            formset = ServicesFormSet(request.POST, instance=server)
            if formset.is_valid():
                server.save()
                form.save_m2m()
                formset.save()
                if server.hosting_provider != Server.OTHER:
                    apis.update_servers()
                messages.add_message(request, messages.SUCCESS, "The server has been successfully created.")
                return HttpResponseRedirect(self.next)
        if request.POST.get("services-TOTAL_FORMS", "0") == "0":
            ServicesFormSet = inlineformset_factory(Server, Service, fields="__all__", extra=1)
            formset = ServicesFormSet()
        else:
            formset = ServicesFormSet(request.POST)
        return render(request=request, template_name="servers/create.html", context={"form": form, "formset": formset})


class DetailView(PermissionsRequiredMixin, AccessModelMixin, View):
    model = Server

    def get(self, request):
        self.server.status_color = apis.get_status_color(self.server)
        return render(request=request, template_name="servers/detail.html", context={"server": self.server})


class EditView(PermissionsRequiredMixin, AccessModelMixin, NextPageMixin, View):
    superuser = True
    model = Server

    def get(self, request):
        form = ServerForm(instance=self.server)
        ServicesFormSet = inlineformset_factory(
            Server, Service, fields="__all__", extra=int(not bool(self.server.services.count()))
        )
        formset = ServicesFormSet(instance=self.server)
        return render(request=request, template_name="servers/edit.html", context={"form": form, "formset": formset})

    def post(self, request):
        form = ServerForm(request.POST, instance=self.server)
        ServicesFormSet = inlineformset_factory(Server, Service, fields="__all__", extra=0)
        formset = ServicesFormSet(request.POST, instance=self.server)
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            messages.add_message(request, messages.SUCCESS, "The server has been successfully edited.")
            return HttpResponseRedirect(self.next)
        if request.POST.get("services-TOTAL_FORMS", "0") == "0":
            ServicesFormSet = inlineformset_factory(Server, Service, fields="__all__", extra=1)
            formset = ServicesFormSet(instance=self.server)
        return render(request=request, template_name="servers/edit.html", context={"form": form, "formset": formset})


class DeleteView(PermissionsRequiredMixin, AccessModelMixin, NextPageMixin, View):
    superuser = True
    model = Server

    def get(self, request):
        return render(request=request, template_name="servers/delete.html")

    def post(self, request):
        self.server.delete()
        messages.add_message(request, messages.SUCCESS, "The server has been deleted.")
        return HttpResponseRedirect(self.next)

business_tracker/apps/servers/templates/servers/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}

{% block title %}Create Server{% endblock title %}
{% block subtitle %}Create a new server.{% endblock subtitle %}

{% block content %}
<form novalidate method="post" action="" id="serverForm">
    {% csrf_token %}
    {{ form|crispy }}
    <table id="id_services_table" class="table">
        <thead>
            <tr>
                <th scope="col" width="25%">Name</th>
                <th scope="col" width="20%" class="item-table">Platform</th>
                <th scope="col" width="25%" class="item-table">URL</th>
                <th scope="col" width="5%"></th>
            </tr>
        </thead>
        <tbody>
            {% for form in formset.forms %}
            {% for field in form.hidden_fields %}{{ field }}{% endfor %}
            <tr id="{{ form.prefix }}-row">
                <td>
                    {% crispy_field form.name 'class' 'form-control form-control-sm' %}
                    {% if form.name.errors %}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                        <strong>{{ error }}</strong>
                        {% endfor %}
                    </div>
                    {% endif %}
                </td>
                <td>
                    {% crispy_field form.platform 'class' 'form-control form-control-sm' %}
                    {% if form.platform.errors %}
                    <div class="invalid-feedback">
                        {% for error in form.platform.errors %}
                        <strong>{{ error }}</strong>
                        {% endfor %}
                    </div>
                    {% endif %}
                </td>
                <td>
                    {% crispy_field form.url 'class' 'form-control form-control-sm' %}
                    {% if form.url.errors %}
                    <div class="invalid-feedback">
                        {% for error in form.url.errors %}
                        <strong>{{ error }}</strong>
                        {% endfor %}
                    </div>
                    {% endif %}
                </td>
                <td class="btn-delete-container">{% if form.instance.pk %}{{ form.DELETE }}{% endif %}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <p>
        {{ formset.management_form }}
    </p>
    <hr>
    <div class="form-actions">
        <button type="submit" class="btn btn-success btn-detail">
            <i class="fas fa-check fa-fw mr-1"></i>
            Save
        </button>
        <a class="btn btn-secondary btn-detail" href="{{ request.GET.next }}">
            <i class="fas fa-times-circle fa-fw mr-1"></i>
            Cancel
        </a>
    </div>
</form>
<script>
    updateInputs();
    $('#id_hosting_provider').on("change", updateInputs);
    $(function () {
        $('#id_services_table tbody tr').formset({
            prefix: 'services'
        })
    });
</script>
{% endblock content %}

business_tracker/apps/servers/templates/servers/delete.html
{% extends "base.html" %}

{% block title %}Delete Server{% endblock title %}
{% block subtitle %}Delete the server and associated data.{% endblock subtitle %}

{% block content %}
<form novalidate method="post">
    {% csrf_token %}
    <div class="form-group">
        <p>
            Are you sure you want to proceed?
            <br>
            This action is <span class="text-danger">irreversible</span>.
        </p>
    </div>
    <hr>
    <div class="form-actions">
        <button type="submit" class="btn btn-danger btn-detail">
            <i class="fas fa-trash fa-fw mr-1"></i>
            Delete
        </button>
        <a class="btn btn-secondary btn-detail" href="{% firstof request.GET.cancel request.GET.next %}">
            <i class="fas fa-times-circle fa-fw mr-1"></i>
            Cancel
        </a>
    </div>
</form>
{% endblock content %}

business_tracker/apps/servers/templates/servers/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ server.label }}{% endblock title %}
{% block subtitle %}View details about the server.{% endblock subtitle %}

{% block content %}
<div class="container-fluid no-gutters">
    <div class="row pt-3">
        <div class="col-xl-6 px-0 pr-xl-3">
            <h2>Server Information</h2>
            <table class="table">
                <tbody>
                    <tr>
                        <th scope="row">Hosting Provider</th>
                        <td>{{ server.get_hosting_provider }}</td>
                    </tr>
                    {% if server.provider_id %}
                    <tr>
                        <th scope="row">Provider ID</th>
                        <td>{{ server.provider_id }}</td>
                    </tr>
                    {% endif %}
                    <tr>
                        <th scope="row">Label</th>
                        <td>{{ server.label }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Operating System</th>
                        <td>{{ server.operating_system }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Specifications</th>
                        <td>{{ server.specifications }}</td>
                    </tr>
                    <tr>
                        <th scope="row">IP Address</th>
                        <td class="d-flex justify-content-between">
                            <p class="m-0 p-0" id="ipAddress">{{ server.ip_address }}</p>
                            <button class="btn btn-sm btn-outline-secondary ml-2" id="ipAddressButton">
                                <i class="fas fa-copy fa-fw"></i>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Root Password</th>
                        <td class="d-flex justify-content-between">
                            <p class="m-0 p-0" id="rootPassword">{{ server.root_password }}</p>
                            <button class="btn btn-sm btn-outline-info ml-2" href="#" data-toggle="button" id="rootPasswordButton">
                                <i class="fas fa-eye fa-fw"></i>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">Price</th>
                        <td>{{ server.price }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Status</th>
                        <td>
                            <span class="badge badge-{{ server.status_color }} font-weight-normal text-uppercase">{{ server.status }}</span>
                            <span class="badge badge-secondary font-weight-normal text-uppercase">{{ server.region }}</span>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-xl-6 px-0 pl-xl-3">
            <h2>Services</h2>
            <table class="table">
                <tbody>
                    {% for service in server.services.all %}
                    <tr>
                        <th scope="row"><a href="{{ service.url }}">{{ service.name }}</a></th>
                        <td>{{ service.platform }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<hr>
<div class="container-fluid no-gutters">
    <div class="row">
        <a class="btn btn-dark btn-detail" href="{% url 'servers:list' %}">
            <i class="fas fa-arrow-left"></i>
        </a>
        {% if server.get_hosting_provider == 0 %}
        <a class="btn btn-primary btn-detail" id="consoleButton"
            href="https://cloud.linode.com/linodes/{{ server.provider_id }}/lish/weblish">
            <i class="fas fa-terminal mr-1"></i>
            Launch Console
        </a>
        {% endif %}
        {% if user.is_superuser %}
        <a class="btn btn-warning btn-detail" href="{% url 'servers:edit' uid=server.uid %}?next={{ request.get_full_path }}">
            <i class="fas fa-pen mr-1"></i>
            Edit Server
        </a>
        <a class="btn btn-danger btn-detail"
            href="{% url 'servers:delete' uid=server.uid %}?next=/servers/&cancel={{ request.get_full_path }}">
            <i class="fas fa-trash mr-1"></i>
            Delete Server
        </a>
        {% endif %}
    </div>
</div>
{% endblock content %}

business_tracker/apps/servers/templates/servers/edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_field %}

{% block title %}Edit Server{% endblock title %}
{% block subtitle %}Edit the server.{% endblock subtitle %}

{% block content %}
<form novalidate method="post" action="" id="serverForm">
    {% csrf_token %}
    {{ form|crispy }}
    <table id="id_services_table" class="table">
        <thead>
            <tr>
                <th scope="col" width="25%">Name</th>
                <th scope="col" width="20%" class="item-table">Platform</th>
                <th scope="col" width="25%" class="item-table">URL</th>
                <th scope="col" width="5%"></th>
            </tr>
        </thead>
        <tbody>
            {% for form in formset.forms %}
            {% for field in form.hidden_fields %}{{ field }}{% endfor %}
            <tr id="{{ form.prefix }}-row">
                <td>
                    {% crispy_field form.name 'class' 'form-control form-control-sm' %}
                    {% if form.name.errors %}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                        <strong>{{ error }}</strong>
                        {% endfor %}
                    </div>
                    {% endif %}
                </td>
                <td>
                    {% crispy_field form.platform 'class' 'form-control form-control-sm' %}
                    {% if form.platform.errors %}
                    <div class="invalid-feedback">
                        {% for error in form.platform.errors %}
                        <strong>{{ error }}</strong>
                        {% endfor %}
                    </div>
                    {% endif %}
                </td>
                <td>
                    {% crispy_field form.url 'class' 'form-control form-control-sm' %}
                    {% if form.url.errors %}
                    <div class="invalid-feedback">
                        {% for error in form.url.errors %}
                        <strong>{{ error }}</strong>
                        {% endfor %}
                    </div>
                    {% endif %}
                </td>
                <td class="btn-delete-container">{% if form.instance.pk %}{{ form.DELETE }}{% endif %}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <p>
        {{ formset.management_form }}
    </p>
    <hr>
    <div class="form-actions">
        <button type="submit" class="btn btn-success btn-detail">
            <i class="fas fa-check fa-fw mr-1"></i>
            Save
        </button>
        <a class="btn btn-secondary btn-detail" href="{{ request.GET.next }}">
            <i class="fas fa-times-circle fa-fw mr-1"></i>
            Cancel
        </a>
    </div>
</form>
<script>
    updateInputs();
    $('#id_hosting_provider').on("change", updateInputs);
    $(function () {
        $('#id_services_table tbody tr').formset({
            prefix: 'services'
        })
    });
</script>
{% endblock content %}

business_tracker/apps/servers/templates/servers/list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Servers{% endblock title %}
{% block subtitle %}View the list of all servers.{% endblock subtitle %}

{% block content %}
<table id="jsTable" class="table list-view nowrap" style="width: 100%;">
    <thead>
        <tr>
            <th scope="col">Label</th>
            <th scope="col">Hosting Provider</th>
            <th scope="col">Status</th>
            <th scope="col">Services</th>
            <th scope="col">
                {% if user.is_superuser %}
                <a class="btn btn-sm btn-success" href="{% url 'servers:create' %}?next={{ request.get_full_path }}">
                    <i class="fas fa-plus fa-fw"></i>
                    Create Server
                </a>
                {% endif %}
            </th>
        </tr>
    </thead>
    <tbody>
        {% for server in servers %}
        <tr>
            <td>
                {{ server.label }}
            </td>
            <td>
                {{ server.get_hosting_provider }}
            </td>
            <td>
                <span class="ml-1 badge badge-{{ server.status_color }} font-weight-normal text-uppercase">{{ server.status }}</span>
                <span class="ml-1 badge badge-secondary font-weight-normal text-uppercase">{{ server.region }}</span>
            </td>
            <td>
                {% for service in server.services.all %}
                <p class="m-0"><a href="{{ service.url }}">{{ service.name }}</a> - {{ service.platform }}</p>
                {% endfor %}
            </td>
            <td>
                <a class="btn btn-sm btn-info" href="{% url 'servers:detail' uid=server.uid %}" data-toggle="tooltip" title="View Server">
                    <i class="fas fa-eye fa-fw"></i>
                </a>
                {% if user.is_superuser %}
                <a class="btn btn-sm btn-warning" href="{% url 'servers:edit' uid=server.uid %}?next={{ request.get_full_path }}"
                    data-toggle="tooltip" title="Edit Server">
                    <i class="fas fa-pen fa-fw"></i>
                </a>
                <a class="btn btn-sm btn-danger" href="{% url 'servers:delete' uid=server.uid %}?next={{ request.get_full_path }}"
                    data-toggle="tooltip" title="Delete Server">
                    <i class="fas fa-trash fa-fw"></i>
                </a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}